### ISSUE TITLE
Test tests::test_schunk_basic fails in --release mode

### ISSUE THREAD

**Issue by musicinmybrain** [milesgranger/blosc2-rs#19]
I’m working on packaging these two crates for Fedora in order to support the latest `libcramjam` and the upcoming `cramjam-python` 2.8.4.

For distribution packaging purposes, my environment has some differences from the upstream development environment. In `blosc2-sys`:

- `Cargo.toml` is patched to make the `bindgen` and `pkg-config` dependencies non-optional.
- The `static` feature is hidden, and `build.rs` is patched (by adjusting the conditionals):
  * Always link the system shared library regardless of features
  * Always re-generate the bindings regardless of features
  * Don’t require the `blosc2` version to exactly match the bundled one; Fedora 39, 40, and 41 have 2.10.5, 2.14.0, and 2.14.4, respectively.
  * Adjust the header path for `bindgen` to point at the system-wide header `/usr/include/blosc2.h`

There might be some further improvements suggested once I get this submitted for package review, but these downstream patches seem to be working as expected, and all the `blosc2-sys` tests pass. There is some discussion of the kind of patching we may need for `-sys` crates in https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/#_rust2rpm.

When I try to build a package for `blosc2-rs` using the `rust-blosc2-sys` package described above, I have exactly one test failure in `tests::test_schunk_basic`. All other tests (including doctests) pass. This happens in Fedora 39, 40, and 41, so it doesn’t appear to be due to differences in the version of the system `blosc2` library.

```
---- tests::test_schunk_basic stdout ----   
thread 'tests::test_schunk_basic' panicked at src/lib.rs:1873:9:
assertion `left == right` failed
  left: 0
 right: 1
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner  
   3: core::panicking::assert_failed
             at /builddir/build/BUILD/rustc-1.77.2-src/library/core/src/panicking.rs:297:5
   4: blosc2::tests::test_schunk_basic
             at ./src/lib.rs:1873:9
   5: blosc2::tests::test_schunk_basic::{{closure}}
             at ./src/lib.rs:1864:31
   6: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rustc-1.77.2-src/library/core/src/ops/function.rs:250:5
```

I know that my configuration is a bit different from the one you are testing and explicitly supporting, but I would really appreciate any advice on understanding the root cause.

**Comment by musicinmybrain** [comment]
I’m especially curious to know if this is the same thing you were seeing when you wrote

https://github.com/milesgranger/blosc2-rs/blob/bb3631458e63a8d9adadf5860935b12e53bbd6f7/src/lib.rs#L1861-L1864

**Comment by milesgranger** [comment]
hehe, what a great and informative comment I've made. :sweat_smile: I thought it was a sigabrt of some type, and [it seems it is here](https://github.com/milesgranger/blosc2-rs/actions/runs/8973148775/job/24642663914?pr=20#step:5:824).

I would set aside some time to debug this tomorrow, but I don't have a Window machine readily available at the moment and it doesn't appear to be what you're experiencing... but maybe in some round about way it is related so I'll poke at it. Still a WIP but felt okay enough to include in libcramjam and thus python cramjam.experimental.

Would it be helpful in the short term to add a feature flag to python cramjam to not build the `cramjam.experimental` module (and thus skip including blosc2)? FWIW, I don't intend on releasing cramjam 2.8.4 anytime soon unless there's some unexpected requests for it out of the pre-release stage. You'll probably notice libcramjam already has a feature flag to avoid blosc2.

**Comment by musicinmybrain** [comment]
> Would it be helpful in the short term to add a feature flag to python cramjam to not build the `cramjam.experimental` module (and thus skip including blosc2)? FWIW, I don't intend on releasing cramjam 2.8.4 anytime soon unless there's some unexpected requests for it out of the pre-release stage. You'll probably notice libcramjam already has a feature flag to avoid blosc2.

Hmm, maybe. But I’ve made the decision to also ship the `libcramjam.so` shared library built with `cargo-c`, so I would also need to do a bit of patching to build a copy of that with the blosc2 part of the API and ABI patched out. That’s probably not too hard.

On the other hand, since there’s no great time pressure, and I’m just trying to make sure everything is lined up to ship a `python-cramjam-2.8.4` update in a vaguely reasonable amount of time after you release it, I think I would be happiest if I can just help understand and patch the problem.

(I can also skip the failing test, but it looks potentially serious enough that I’m not convinced that is a good idea.)

**Comment by milesgranger** [comment]
Yep, I agree. Let's try to figure this out. IMO skipping it is okay-ish as we're 0.x.x version, but we'll do our best to avoid that. Can you point me to the code you're using if possible? I don't see the branch on your current fork. I have fedora locally so I *should* be able to reproduce it.

**Comment by milesgranger** [comment]
I added a [docker-fedora run](https://github.com/milesgranger/blosc2-rs/pull/20/commits/ec123c48476c4168133eed2ded015b63948d9036) and that [also seems fine,](https://github.com/milesgranger/blosc2-rs/actions/runs/8979530083/job/24661680879) but maybe it's helpful for you if you want to run your modified code on it?

**Comment by musicinmybrain** [comment]
Neither package is in Fedora yet: I’ve submitted `rust-blosc2-sys` [for package review](https://bugzilla.redhat.com/show_bug.cgi?id=2279337) here, and I haven’t submitted `rust-blosc2-rs` yet.

I just managed to reproduce this in a git checkout without having to build a package, which should be very helpful. The fork https://github.com/musicinmybrain/blosc2-rs/tree/fedora-as-packaged basically corresponds to the downstream modifications to build with the system blosc2 and always use pkg-config and bindgen. This passes `cargo test`, but fails in the exact way I was seeing when I try `cargo test --release`.

Now that I know `cargo test --release` is required, I can reproduce this on bb3631458e63a8d9adadf5860935b12e53bbd6f7 with the bundled blosc2, which suggests the problem likely has nothing to do with Fedora.

**Comment by milesgranger** [comment]
Oh goodness, okay yeah I see now it fails with `--release`... :face_exhaling:

**Comment by milesgranger** [comment]
Ought to be fixed now. When you have time to check out latest on main (https://github.com/milesgranger/blosc2-rs/commit/314c4d10493e271af63a2ddace298ca3ffb0d9cf), and it works I'll publish a release.

**Comment by musicinmybrain** [comment]
Nice debugging!

I assume you’ve already tested https://github.com/milesgranger/blosc2-rs/pull/22 adequately in a git checkout, so I quickly hacked up https://github.com/milesgranger/blosc2-rs/pull/22.patch to include only the changes to `src/lib.rs` and built an RPM package with it locally using `mock`. Everything looked good, so I tried it [in COPR](https://copr.fedorainfracloud.org/coprs/music/libcramjam/build/7425007/) for all architectures and Fedora releases. A few of the builds are still pending or running, but it looks like everything is going to be OK there too as long as there aren’t any endian issues on s390x.

Thanks again for digging into this!

**Comment by musicinmybrain** [comment]
Oof: [there *is* a problem on `s390x`](https://download.copr.fedorainfracloud.org/results/music/libcramjam/fedora-39-s390x/07425007-rust-blosc2-rs/builder-live.log.gz). I should probably open a separate issue for that, though.

**Comment by musicinmybrain** [comment]
> Oof: [there _is_ a problem on `s390x`](https://download.copr.fedorainfracloud.org/results/music/libcramjam/fedora-39-s390x/07425007-rust-blosc2-rs/builder-live.log.gz). I should probably open a separate issue for that, though.

https://github.com/milesgranger/blosc2-rs/issues/23
